<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #333; margin: 0; padding: 20px; }
        .header { text-align: center; margin-bottom: 20px; padding-bottom: 15px; border-bottom: 3px solid #E91E8C; }
        .header img { max-height: 50px; margin-bottom: 8px; }
        .header h1 { font-size: 20px; color: #1a1a2e; margin: 4px 0; }
        .header .subtitle { font-size: 12px; color: #777; }
        .section { margin-bottom: 20px; }
        .section-title { font-size: 14px; font-weight: bold; color: #1a1a2e; padding: 8px 12px; background: #f0f0f5; border-left: 4px solid #E91E8C; margin-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
        .info-table td { padding: 6px 10px; border-bottom: 1px solid #eee; font-size: 11px; }
        .info-table td.label { font-weight: bold; color: #555; width: 40%; background: #fafafa; }
        .info-table td.value { color: #1a1a2e; }
        .checklist-table { border: 1px solid #ddd; }
        .checklist-table th { background: #1a1a2e; color: #fff; padding: 8px 10px; font-size: 11px; text-align: left; }
        .checklist-table td { padding: 8px 10px; border-bottom: 1px solid #eee; font-size: 11px; }
        .checklist-table tr:nth-child(even) { background: #fafafa; }
        .status-completed { color: #28a745; font-weight: bold; }
        .status-pending { color: #dc3545; }
        .status-skipped { color: #ffc107; }
        .footer { margin-top: 20px; padding-top: 10px; border-top: 2px solid #eee; font-size: 10px; color: #999; text-align: center; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 10px; font-weight: bold; }
        .meta-grid { display: table; width: 100%; }
        .meta-cell { display: table-cell; padding: 8px; text-align: center; }
        .meta-cell .val { font-size: 16px; font-weight: bold; color: #1a1a2e; }
        .meta-cell .lbl { font-size: 10px; color: #777; text-transform: uppercase; }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        @if($logoBase64)
            <img src="{{ $logoBase64 }}" alt="Logo">
        @endif
        <h1>INTERNAL JOB CARD PACK</h1>
        <div class="subtitle">{{ $companySettings['company_name'] ?? '' }}</div>
    </div>

    <!-- Job Card Summary -->
    <div class="section">
        <div class="section-title">Job Card Details</div>
        <table class="info-table">
            <tr><td class="label">Job Code</td><td class="value">{{ $jobCard->job_code }}</td></tr>
            <tr><td class="label">Job Type</td><td class="value">{{ $jobType->name ?? '' }}</td></tr>
            <tr><td class="label">Status</td><td class="value">{{ ucfirst($jobCard->status) }}</td></tr>
            <tr><td class="label">Priority</td><td class="value">{{ ucfirst($jobCard->priority) }}</td></tr>
            <tr><td class="label">Due Date</td><td class="value">{{ $jobCard->due_date ? \Carbon\Carbon::parse($jobCard->due_date)->format('d/m/Y') : 'N/A' }}</td></tr>
            <tr><td class="label">Completion</td><td class="value">{{ number_format($jobCard->completion_percentage, 0) }}%</td></tr>
            <tr><td class="label">Created</td><td class="value">{{ \Carbon\Carbon::parse($jobCard->created_at)->format('d/m/Y H:i') }}</td></tr>
            <tr><td class="label">Generated By</td><td class="value">{{ $generatedBy }} on {{ $generatedAt }}</td></tr>
        </table>
    </div>

    <!-- Client Information -->
    <div class="section">
        <div class="section-title">Client Information</div>
        <table class="info-table">
            <tr><td class="label">Company Name</td><td class="value">{{ $client->company_name ?? '' }}</td></tr>
            <tr><td class="label">Client Code</td><td class="value">{{ $client->client_code ?? '' }}</td></tr>
            @foreach($fields as $f)
            <tr><td class="label">{{ $f->field_label }}</td><td class="value">{{ $f->value ?: 'N/A' }}</td></tr>
            @endforeach
        </table>
    </div>

    <!-- Checklist Progress -->
    <div class="section">
        <div class="section-title">Checklist Progress</div>
        <table class="checklist-table">
            <thead>
                <tr>
                    <th style="width:40px;">#</th>
                    <th>Step</th>
                    <th style="width:80px;">Type</th>
                    <th style="width:80px;">Required</th>
                    <th style="width:90px;">Status</th>
                    <th style="width:120px;">Completed By</th>
                    <th style="width:100px;">Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach($progress as $i => $step)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $step->step_name }}</td>
                    <td>{{ $step->step_type }}</td>
                    <td>{{ $step->is_required ? 'Yes' : 'No' }}</td>
                    <td class="status-{{ $step->status }}">{{ ucfirst($step->status) }}</td>
                    <td>{{ $step->completed_by_name ?? '-' }}</td>
                    <td>{{ $step->completed_at ? \Carbon\Carbon::parse($step->completed_at)->format('d/m/Y H:i') : '-' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Notes -->
    @if($jobCard->notes)
    <div class="section">
        <div class="section-title">Notes</div>
        <p>{{ $jobCard->notes }}</p>
    </div>
    @endif

    <!-- Attachments -->
    @if($attachments->count())
    <div class="section">
        <div class="section-title">Attached Documents</div>
        <table class="checklist-table">
            <thead>
                <tr><th>File</th><th>Type</th><th>Date</th></tr>
            </thead>
            <tbody>
                @foreach($attachments as $att)
                <tr>
                    <td>{{ $att->file_original_name ?? $att->file_name }}</td>
                    <td>{{ $att->file_type }}</td>
                    <td>{{ \Carbon\Carbon::parse($att->created_at)->format('d/m/Y H:i') }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    <div class="footer">
        <p>Internal Job Card Pack — {{ $companySettings['company_name'] ?? '' }} — Generated {{ $generatedAt }}</p>
        <p>This is an internal document and is confidential.</p>
    </div>
</body>
</html>
